pipeline:
  run tests:
    image: node
    commands:
      - yarn
      - yarn run lint
      - yarn run test:coverage
    when:
      event: push
  sonar:
    image: newtmitch/sonar-scanner
    commands:
      - echo $PWD
      - sonar-scanner
    secrets: [SONAR_HOST, SONAR_LOGIN]
    when:
      event: push
  notify:
    image: drillster/drone-email
    host: smtp.sendgrid.net
    port: 2525
    username: apikey
    from: drone@modell-aachen.de
    secrets: [EMAIL_PASSWORD]
    recipients:
      - entwickler@modell-aachen.de
    recipients_only: true
    when:
      event: push
      status: changed
