pipeline:
  run tests:
    image: node:12
    commands:
      - yarn
      - yarn lint
      - yarn test:unit --coverage
    when:
      event: push
  notify:
    image: drillster/drone-email
    host: smtp.sendgrid.net
    port: 2525
    username: apikey
    from: drone@modell-aachen.de
    secrets: [EMAIL_PASSWORD]
    recipients:
      - entwickler@modell-aachen.de
    recipients_only: true
    when:
      event: push
      status: changed
